apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      volumes:
        - name: hash-volume
          persistentVolumeClaim:
              claimName: hash-claim
      containers:
        - name: pingpong-app
          image: partanenjoonas/pingpong-app:2.01.2
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: hash-volume
