apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app-dep
  namespace: main-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      volumes:
        - name: pingpong-volume
          persistentVolumeClaim:
              claimName: pingpong-claim
      containers:
        - name: pingpong-app
          image: partanenjoonas/pingpong-app:3.02
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: pingpong-volume
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pw
                  key: POSTGRES_PASSWORD
          envFrom:
          - configMapRef:
              name: postgres-configuration

