apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingpong-app-hpa
  namespace: main-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pingpong-app-dep
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 30
