apiVersion: v1
kind: Service
metadata:
  name: pingpong-app-svc
  namespace: main-namespace
spec:
  type: NodePort
  selector:
    app: pingpong-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
