apiVersion: v1
kind: Service
metadata:
  name: pingpong-app-svc
  namespace: main-namespace
spec:
  type: ClusterIP
  selector:
    app: pingpong-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080