apiVersion: v1
kind: ConfigMap
metadata:
  name: tododb-configuration
  namespace: todo-namespace
  labels:
    app: tododb
data:
  POSTGRES_DB: tododb
  POSTGRES_USER: dbadmin
  POSTGRES_HOST: tododb-svc
  POSTGRES_PORT: '5432'
