apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: todo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: images-volume
          persistentVolumeClaim:
              claimName: images-claim
      containers:
        - name: todo-app
          image: partanenjoonas/todo-app:1.0.6
          volumeMounts:
            - mountPath: /usr/src/app/images
              name: images-volume
