apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: todo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: images-volume
          persistentVolumeClaim:
              claimName: images-claim
      containers:
        - name: todo-app
          image: partanenjoonas/todo-app:2.10
          volumeMounts:
            - mountPath: /usr/src/app/images
              name: images-volume
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tododb-password
                  key: POSTGRES_PASSWORD
          envFrom:
          - configMapRef:
              name: tododb-configuration