apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todo-app-ingress
  namespace: todo-namespace
spec:
  backend:
    serviceName: todo-app-client-svc
    servicePort: 80
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: todo-app-client-svc
          servicePort: 80
      - path: /api/*
        backend:
          serviceName: todo-app-svc
          servicePort: 80