apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
  namespace: todo-namespace
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - port: 2348
      protocol: TCP
      targetPort: 8050
