apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-client-dep
  namespace: todo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-client
  template:
    metadata:
      labels:
        app: todo-app-client
    spec:
      containers:
        - name: todo-app-client
          image: TODOAPP/CLIENT
