apiVersion: v1
kind: Service
metadata:
  name: todo-app-client-svc
  namespace: todo-namespace
spec:
  type: NodePort
  selector:
    app: todo-app-client
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8040
