apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: todo-cronjob
  namespace: todo-namespace
spec:
  schedule: '0 10 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-cronjob
              image: partanenjoonas/todo-reminder:2.08.7
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
