apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/dbconfigmap.yaml
  - manifests/sealedsecret.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/persistentvolume.yaml
  - manifests/statefulset.yaml
  - manifests/ingress.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml