apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-apps-dep
  namespace: main-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-apps
  template:
    metadata:
      labels:
        app: main-apps
    spec:
      volumes:
        - name: hash-volume
          persistentVolumeClaim:
              claimName: hash-claim
      containers:
        - name: main-app-writer
          image: partanenjoonas/main-app-writer:1.10.3
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: hash-volume
        - name: main-app-reader
          image: partanenjoonas/main-app-reader:2.06
          env:
            - name: MESSAGE
              valueFrom:
                  configMapKeyRef:
                    name: dotenv-configmap
                    key: message
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: hash-volume
