apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: main-apps-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: main-apps-dep
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
