apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main-app-ingress
  namespace: main-namespace
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: main-apps-svc
              servicePort: 80
          - path: /pingpong
            backend:
              serviceName: pingpong-app-svc
              servicePort: 80
