apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main-app-ingress
  namespace: main-namespace
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: main-apps-svc
          servicePort: 2345
      - path: /todoapp
        backend:
          serviceName: todo-app-client-svc
          servicePort: 2347
      - path: /todoapp/api
        backend:
          serviceName: todo-app-svc
          servicePort: 2348