apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hash-claim
  namespace: main-namespace
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
