apiVersion: v1
kind: Service
metadata:
  name: main-apps-svc
  namespace: main-namespace
spec:
  type: LoadBalancer
  selector:
    app: main-apps
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8000