name: Delete environment on branch delete

on: delete

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  SERVER_IMAGE: todo-app
  CLIENT_IMAGE: todo-app-client

jobs:
  delete-environment:
    name: Delete environment on branch delete
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: todo-app

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - run: gcloud --quiet auth configure-docker
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Delete resources
        run: kubectl delete namespace ${GITHUB_REF#refs/heads/} || true
