name: Deploy to GKE

on:
  push:

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  SERVER_IMAGE: todo-app
  CLIENT_IMAGE: todo-app-client

jobs:
  build-publish-deploy-server:
    name: Build, publish, and deploy the server app
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: todo-app/server

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - run: gcloud --quiet auth configure-docker
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Create image name and tag
        run: echo "SERVER_IMAGE_WITH_TAG=gcr.io/${{ secrets.GKE_PROJECT }}/$SERVER_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
      - name: Build
        run: docker build --tag "$SERVER_IMAGE_WITH_TAG" .
      - name: Publish
        run: docker push "$SERVER_IMAGE_WITH_TAG"
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      - name: Deploy
        run: |-
          ./kustomize edit set image TODOAPP/SERVER=$SERVER_IMAGE_WITH_TAG
          kubectl create namespace todo-namespace
          kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.12.1/controller.yaml
          kubectl apply -k .
          kubectl rollout status deployment $SERVER_IMAGE

  build-publish-deploy-client:
    name: Build, publish, and deploy the client app
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: todo-app/client

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - run: gcloud --quiet auth configure-docker
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Create image name and tag
        run: echo "CLIENT_IMAGE_WITH_TAG=gcr.io/${{ secrets.GKE_PROJECT }}/$CLIENT_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
      - name: Build
        run: docker build --tag "$CLIENT_IMAGE_WITH_TAG" .
      - name: Publish
        run: docker push "$CLIENT_IMAGE_WITH_TAG"
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      - name: Deploy
        run: |-
          ./kustomize edit set image TODOAPP/CLIENT=$CLIENT_IMAGE_WITH_TAG
          kubectl apply -k .
          kubectl rollout status deployment $CLIENT_IMAGE
